# Generated by Django 4.2.20 on 2025-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('summ', models.PositiveIntegerField(blank=True, null=True, verbose_name='Желаемый бюджет')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана ли заявка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'leads',
                'ordering': ('-created_at',),
            },
        ),
    ]
